### ISSUE TITLE
npm errors

### ISSUE THREAD

**Issue by sagarmakar** [veeralsharma/MERN-STACK-Arogyasetu-clone-Am-i-safe-#1]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arogya-setu@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the arogya-setu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-31T17_58_42_056Z-debug.log

**Comment by veeralsharma** [comment]
ensure you have first run npm install in your server and client directory 
If you have correctly done that  you must be having node modules folder in main directory and client directory
If you have done that correctly

Follow these steps 
npm cache clean --force
delete node_modules folder
delete package-lock.json file
npm install
